version: '3.6'
services:
    jenkins-app:
        container_name: jenkins
        image: onedsol/jenkins-docker:latest
        ports:
            - 8080:8080
        environment:
            TZ: "America/New_York"
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - data:/var/jenkins_home
volumes:
    data:
